from PySide6.QtCore import Qt
from PySide6.QtWidgets import QGroupBox, QHBoxLayout, QLabel, QVBoxLayout, QWidget


class EMSMonitorTab(QWidget):
    def __init__(self, host):
        super().__init__()
        self.host = host
        self._build_ui()

    def _build_ui(self):
        layout_mon_main = QVBoxLayout(self)
        h_mon_split = QHBoxLayout()

        layout_mon_left = QVBoxLayout()
        self.host.group_ems_params = QGroupBox("EMS实时采集参数")
        layout_grid = QVBoxLayout(self.host.group_ems_params)

        row1_layout = QHBoxLayout()
        self.host.group_voltage = QGroupBox("电压(V)")
        layout_voltage = QVBoxLayout(self.host.group_voltage)
        self.host.label_dc_volt_val = QLabel("00.00")
        self.host.label_dc_volt_val.setObjectName("label_dc_volt_val")
        self.host.label_dc_volt_val.setStyleSheet("font: 26pt 'Microsoft YaHei UI'; color: #0052D9; font-weight: bold;")
        self.host.label_dc_volt_val.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout_voltage.addWidget(self.host.label_dc_volt_val)
        row1_layout.addWidget(self.host.group_voltage)

        self.host.group_current = QGroupBox("电流(A)")
        layout_current = QVBoxLayout(self.host.group_current)
        self.host.label_dc_current_val = QLabel("00.00")
        self.host.label_dc_current_val.setObjectName("label_dc_current_val")
        self.host.label_dc_current_val.setStyleSheet("font: 26pt 'Microsoft YaHei UI'; color: #D97706; font-weight: bold;")
        self.host.label_dc_current_val.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout_current.addWidget(self.host.label_dc_current_val)
        row1_layout.addWidget(self.host.group_current)

        row2_layout = QHBoxLayout()
        self.host.group_power = QGroupBox("功率(KW)")
        layout_power = QVBoxLayout(self.host.group_power)
        self.host.label_power_val = QLabel("00.00")
        self.host.label_power_val.setObjectName("label_power_val")
        self.host.label_power_val.setStyleSheet("font: 26pt 'Microsoft YaHei UI'; color: #059669; font-weight: bold;")
        self.host.label_power_val.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout_power.addWidget(self.host.label_power_val)
        row2_layout.addWidget(self.host.group_power)

        self.host.group_fault = QGroupBox("故障字")
        layout_fault = QVBoxLayout(self.host.group_fault)
        self.host.label_fault_val = QLabel("0000")
        self.host.label_fault_val.setObjectName("label_fault_val")
        self.host.label_fault_val.setStyleSheet("font: 26pt 'Microsoft YaHei UI'; color: #4B5563; font-weight: bold;")
        self.host.label_fault_val.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout_fault.addWidget(self.host.label_fault_val)
        row2_layout.addWidget(self.host.group_fault)

        layout_grid.addLayout(row1_layout)
        layout_grid.addLayout(row2_layout)
        layout_mon_left.addWidget(self.host.group_ems_params)

        self.host.group_ems_config = QGroupBox("EMS可配置参数")
        layout_config_main = QVBoxLayout(self.host.group_ems_config)

        self.host.group_device_config = QGroupBox("设备配置")
        layout_device = QVBoxLayout(self.host.group_device_config)
        h_device1 = QHBoxLayout()

        v_device_type = QVBoxLayout()
        lbl_device_type_name = QLabel("设备类型")
        lbl_device_type_name.setStyleSheet("color: #666666; font-size: 9pt;")
        lbl_device_type_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.host.label_device_type_val = QLabel("--")
        self.host.label_device_type_val.setObjectName("label_device_type_val")
        self.host.label_device_type_val.setStyleSheet("font: 12pt 'Microsoft YaHei UI'; color: #2C3E50; font-weight: bold;")
        self.host.label_device_type_val.setAlignment(Qt.AlignmentFlag.AlignCenter)
        v_device_type.addWidget(lbl_device_type_name)
        v_device_type.addWidget(self.host.label_device_type_val)
        h_device1.addLayout(v_device_type)

        v_protocol_ver = QVBoxLayout()
        lbl_protocol_ver_name = QLabel("协议版本")
        lbl_protocol_ver_name.setStyleSheet("color: #666666; font-size: 9pt;")
        lbl_protocol_ver_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.host.label_protocol_ver_val = QLabel("--")
        self.host.label_protocol_ver_val.setObjectName("label_protocol_ver_val")
        self.host.label_protocol_ver_val.setStyleSheet("font: 12pt 'Microsoft YaHei UI'; color: #2C3E50; font-weight: bold;")
        self.host.label_protocol_ver_val.setAlignment(Qt.AlignmentFlag.AlignCenter)
        v_protocol_ver.addWidget(lbl_protocol_ver_name)
        v_protocol_ver.addWidget(self.host.label_protocol_ver_val)
        h_device1.addLayout(v_protocol_ver)

        layout_device.addLayout(h_device1)
        layout_config_main.addWidget(self.host.group_device_config)

        self.host.group_grid_params = QGroupBox("电网参数")
        layout_grid_params = QVBoxLayout(self.host.group_grid_params)
        h_grid1 = QHBoxLayout()

        v_rated_volt = QVBoxLayout()
        lbl_rated_volt_name = QLabel("额定电压(V)")
        lbl_rated_volt_name.setStyleSheet("color: #666666; font-size: 9pt;")
        lbl_rated_volt_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.host.label_rated_volt_val = QLabel("--")
        self.host.label_rated_volt_val.setObjectName("label_rated_volt_val")
        self.host.label_rated_volt_val.setStyleSheet("font: 12pt 'Microsoft YaHei UI'; color: #0066CC; font-weight: bold;")
        self.host.label_rated_volt_val.setAlignment(Qt.AlignmentFlag.AlignCenter)
        v_rated_volt.addWidget(lbl_rated_volt_name)
        v_rated_volt.addWidget(self.host.label_rated_volt_val)
        h_grid1.addLayout(v_rated_volt)

        v_power_factor = QVBoxLayout()
        lbl_power_factor_name = QLabel("功率因数")
        lbl_power_factor_name.setStyleSheet("color: #666666; font-size: 9pt;")
        lbl_power_factor_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.host.label_power_factor_val = QLabel("--")
        self.host.label_power_factor_val.setObjectName("label_power_factor_val")
        self.host.label_power_factor_val.setStyleSheet("font: 12pt 'Microsoft YaHei UI'; color: #FF9800; font-weight: bold;")
        self.host.label_power_factor_val.setAlignment(Qt.AlignmentFlag.AlignCenter)
        v_power_factor.addWidget(lbl_power_factor_name)
        v_power_factor.addWidget(self.host.label_power_factor_val)
        h_grid1.addLayout(v_power_factor)

        layout_grid_params.addLayout(h_grid1)
        layout_config_main.addWidget(self.host.group_grid_params)

        self.host.group_energy_stats = QGroupBox("能量统计")
        layout_energy = QVBoxLayout(self.host.group_energy_stats)
        h_energy1 = QHBoxLayout()

        v_day_power = QVBoxLayout()
        lbl_day_power_name = QLabel("每日发电(Wh)")
        lbl_day_power_name.setStyleSheet("color: #666666; font-size: 9pt;")
        lbl_day_power_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.host.label_day_power_val = QLabel("--")
        self.host.label_day_power_val.setObjectName("label_day_power_val")
        self.host.label_day_power_val.setStyleSheet("font: 12pt 'Microsoft YaHei UI'; color: #27AE60; font-weight: bold;")
        self.host.label_day_power_val.setAlignment(Qt.AlignmentFlag.AlignCenter)
        v_day_power.addWidget(lbl_day_power_name)
        v_day_power.addWidget(self.host.label_day_power_val)
        h_energy1.addLayout(v_day_power)

        v_adjust_ah = QVBoxLayout()
        lbl_adjust_ah_name = QLabel("调整AH")
        lbl_adjust_ah_name.setStyleSheet("color: #666666; font-size: 9pt;")
        lbl_adjust_ah_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.host.label_adjust_ah_val = QLabel("--")
        self.host.label_adjust_ah_val.setObjectName("label_adjust_ah_val")
        self.host.label_adjust_ah_val.setStyleSheet("font: 12pt 'Microsoft YaHei UI'; color: #6C5CE7; font-weight: bold;")
        self.host.label_adjust_ah_val.setAlignment(Qt.AlignmentFlag.AlignCenter)
        v_adjust_ah.addWidget(lbl_adjust_ah_name)
        v_adjust_ah.addWidget(self.host.label_adjust_ah_val)
        h_energy1.addLayout(v_adjust_ah)

        layout_energy.addLayout(h_energy1)
        layout_config_main.addWidget(self.host.group_energy_stats)
        layout_mon_left.addWidget(self.host.group_ems_config)

        layout_mon_right = QVBoxLayout()
        self.host.group_status = QGroupBox("EMS运行状态参数")
        lay_status_inner = QVBoxLayout(self.host.group_status)

        self.host.group_conn_status = QGroupBox("连接状态")
        layout_conn_status = QVBoxLayout(self.host.group_conn_status)
        self.host.label_run_status_val = QLabel("待机")
        self.host.label_run_status_val.setObjectName("label_run_status_val")
        self.host.label_run_status_val.setStyleSheet("font: 16pt 'Microsoft YaHei UI'; color: #64748B; font-weight: bold;")
        self.host.label_run_status_val.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout_conn_status.addWidget(self.host.label_run_status_val)
        lay_status_inner.addWidget(self.host.group_conn_status)

        self.host.group_sys_time = QGroupBox("系统时间")
        layout_sys_time = QVBoxLayout(self.host.group_sys_time)
        self.host.label_sys_time_val = QLabel("00:00:00")
        self.host.label_sys_time_val.setObjectName("label_sys_time_val")
        self.host.label_sys_time_val.setStyleSheet("font: 16pt 'Microsoft YaHei UI'; color: #1E293B; font-weight: bold;")
        self.host.label_sys_time_val.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout_sys_time.addWidget(self.host.label_sys_time_val)
        lay_status_inner.addWidget(self.host.group_sys_time)

        self.host.group_temperature = QGroupBox("温度监测")
        layout_temperature = QVBoxLayout(self.host.group_temperature)
        h_temp_layout = QHBoxLayout()

        v_temp_igbt = QVBoxLayout()
        label_igbt_name = QLabel("IGBT温度")
        label_igbt_name.setStyleSheet("color: #666666; font-size: 9pt;")
        label_igbt_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.host.label_temp_igbt_val = QLabel("00 °C")
        self.host.label_temp_igbt_val.setObjectName("label_temp_igbt_val")
        self.host.label_temp_igbt_val.setStyleSheet("font: 14pt 'Microsoft YaHei UI'; color: #F59E0B; font-weight: bold;")
        self.host.label_temp_igbt_val.setAlignment(Qt.AlignmentFlag.AlignCenter)
        v_temp_igbt.addWidget(label_igbt_name)
        v_temp_igbt.addWidget(self.host.label_temp_igbt_val)
        h_temp_layout.addLayout(v_temp_igbt)

        v_temp_rad = QVBoxLayout()
        label_rad_name = QLabel("散热器温度")
        label_rad_name.setStyleSheet("color: #666666; font-size: 9pt;")
        label_rad_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.host.label_temp_radiator_val = QLabel("00 °C")
        self.host.label_temp_radiator_val.setObjectName("label_temp_radiator_val")
        self.host.label_temp_radiator_val.setStyleSheet("font: 14pt 'Microsoft YaHei UI'; color: #10B981; font-weight: bold;")
        self.host.label_temp_radiator_val.setAlignment(Qt.AlignmentFlag.AlignCenter)
        v_temp_rad.addWidget(label_rad_name)
        v_temp_rad.addWidget(self.host.label_temp_radiator_val)
        h_temp_layout.addLayout(v_temp_rad)

        layout_temperature.addLayout(h_temp_layout)
        lay_status_inner.addWidget(self.host.group_temperature)

        self.host.group_fault_code = QGroupBox("故障码")
        layout_fault_code = QVBoxLayout(self.host.group_fault_code)
        self.host.label_fault_code = QLabel("0000")
        self.host.label_fault_code.setObjectName("label_fault_code")
        self.host.label_fault_code.setStyleSheet("font: 16pt 'Microsoft YaHei UI'; color: #EF4444; font-weight: bold;")
        self.host.label_fault_code.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout_fault_code.addWidget(self.host.label_fault_code)
        lay_status_inner.addWidget(self.host.group_fault_code)

        layout_mon_right.addWidget(self.host.group_status, 3)
        layout_mon_right.addWidget(QGroupBox("杂项参数"), 1)

        h_mon_split.addLayout(layout_mon_left, 3)
        h_mon_split.addLayout(layout_mon_right, 2)
        layout_mon_main.addLayout(h_mon_split)
